### PR TITLE
Implement "Popular Movies" syncing

### PR DESCRIPTION
**Pull request by Technifocal**
This pull request implements "Popular Movies" syncing, as per requested in #182 and #172.

Few key points I want to make clear:

1. I tried to duplicate the already-existing programming style as much as possible
2. This has the "Popular Movie" URL hard-coded, and could be changed to a config option if requested, however @sjlu has stated in #182 that using the URL is fine.
3. No error correction/handling is performed if the configuration file doesn't store an integer for the `popularmoviesfrequency` value, however, the imdb sync code I based this from also didn't handle that, so I assumed it'd be okay
4. This also fixes the hard-coded synchronization time of six hours for the IMDB synchronization script.
5. I placed the code in the `rss` folder, despite the feed not being rss. I did this because they're serving the same function, and I thought it'd be clutterful to add another directory, and felt like generalization was better in this situtation

I understand that @nosmokingbandit has previously stated they don't want to make Watcher "feature rich", and rather stick with the basics and do it well, so I completely understand if this pull request is rejected.

### CODE REVIEW

**Comment by nosmokingbandit** [comment]
Resubmit this to the `testing` branch and I'll check it out.

**Comment by Technifocal** [comment]
Sorry, not going to lie, I am completely new to git/github for submitting code to other projects.

Would you like me to create a pull request of my master branch against your testing branch? This will implement a lot of differences, rather than just my code, as your master and testing branches are out of synchronzation. I'm assuming this is what you want, as the testing branch seems to be out of date and as it's a testing branch, "who cares", but I'd just like to verify. As they say, measure twice, cut once.

**Comment by nosmokingbandit** [comment]
Github is a pain to learn. I'm still not 100% sure what half the stuff does.

If you submit it to my testing branch I can fix conflicts while I merge, then test it locally before sending it out into the wild.

You can submit a pull request for just the files you changed. So rather than asking me to pull your entire fork, just submit scheduler.py, base_config.cfg, etc.

**Comment by Technifocal** [comment]
I couldn't work out how to select single files, so I just used `git cherry-pick` to pull my commits into the testing branch, however, now there are conflicts. I will attempt to resolve those, then submit a pull request.

**Comment by sjlu** [comment]
So it's recommended that you poll this only once a day since this list only updates once a day. 15 minutes seems to be overkill.

**Pull request closed without merging**
