### PR TITLE
Update sabnzbd.py

### PR DESCRIPTION
**Pull request by Scoboose**
Fixes `KeyError: 'watcherkey'`

### CODE REVIEW

**Comment by soundjester** [comment]
This won't work.  The code further down lists `watcherapi = conf['watcherkey']` (line 32) so the configuration variable cannot be renamed without breaking the dependent functions (line 70).

Was the key name causing an error for you? Can you post the error?

**Comment by Scoboose** [comment]
> This won't work. The code further down lists watcherapi = conf['watcherkey'] (line 32) so the configuration variable cannot be renamed without breaking the dependent functions (line 70).

On line 32 `watcherapi = conf['watcherkey']` it is looking for watcherkey but watcher key is not in the conf.  All I did was change the conf to watherkey.  My change has no effect on line 70 because line 70 is pulling the info from the variable that is now set correctly on line 32.

I will be 100% honest, I do not know a whole lot about programming or scripting but this change fixed all my issues with post possessing.

**Comment by soundjester** [comment]
No, you are correct and this PR is correct.

I could've sworn to you that this was fixed in a previous commit, but now I can't find it.

**Comment by nosmokingbandit** [comment]
Fixed in commit https://github.com/nosmokingbandit/watcher/commit/c42d23bdd0200f90e8209453e949331a4d44d445

I didn't accept your pull request because I want to use the var name 'watcherapi' throughout so there is consistency between this and the nzbget post-script.

I don't know where this even came from. It was working at one point and I don't recall changing it. Though I had been taking a large amount of cough syrup over the weekend, so who knows what I did...

Anyway, this should take care of it. Thanks for pointing it out.

**Pull request closed without merging**
