### PR TITLE
Implement "Popular Movies" syncing - Testing

### PR DESCRIPTION
**Pull request by Technifocal**
This is identical to #194, except aimed at the testing branch. Only difference is 23e32fdb65c0537239f48c7d9e8455c0ac3ce573, which is a temporary work around for the new configuration file. I haven't tested or looked into it at all. I only deleted the offending line. The fix for this is identical to the fix for #199, so once that is fixed, I will apply the fix here too.

### CODE REVIEW

**Comment by Technifocal** [comment]
As #199 has now been fixed, I have pushed that fix into `popularmovies.py`.

**Comment by sjlu** [comment]
Hey @Technifocal, can increase the polling rate to something > 6 hours? This list only updates once a day.

**Comment by Technifocal** [comment]
@sjlu Done in 9fea92f5cdb11a3614618eae0cab3a4007c9eabf, sorry for the delay.

**Comment by sjlu** [comment]
All good 👍 

Thanks!

**Comment by nosmokingbandit** [comment]
FYI, I'm going to pull this into testing sometime soon. I changed the entire config system, so I'll need to change a few odds and ends, but its no big deal.

I'm probably going to restrict it to one call every 24 hours. If the information only changes once a day there is no benefit to more frequent calls.

**Comment by Technifocal** [comment]
@nosmokingbandit I saw that change, I was going to remerge/resolve everything for the new configuration, however, I wasn't sure what was happening due to the lack of communication. If you don't have plans of pulling this anytime soon, I probably am not going to bother then.

Which of the following should I do?

* Close this pull request and forget about it
* Close this pull request, update this pull request to the newest version of Watcher's testing branch, then create a new pull request
* Leave the pull request open and update it to the newest version
* Just leave it open as-is

**Comment by nosmokingbandit** [comment]
Leave it open, but don't modify anything.

I'm working on proxy support, which I hope to have done tonight if I can get a reliable socks5 connection.

Once that it done I'll pull your request and start merging it.

**Pull request merged**
